/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package lsann;

import org.junit.Assert;
import org.junit.Test;
import java.io.*;
import static org.junit.Assert.*;


public class AppTest {
    @Test public void testScanSelf() {

        try {
            JarUtil jutil = new JarUtil(false);
            jutil.process("./build/classes", new VisitClassInJarImp());
        } catch(java.io.IOException ex) {
            ex.printStackTrace();
            Assert.fail();
        }
    }

    // following declarations are for testing purposes only, so that this test has something to report.

}
